# Generated by Django 3.2.9 on 2021-11-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audios',
            name='text',
            field=models.TextField(default='no text entered'),
        ),
    ]
