# Generated by Django 3.2.9 on 2021-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_audios_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audios',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
