# Generated by Django 3.2.9 on 2021-11-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_alter_audios_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='audios',
            name='from_tel',
            field=models.CharField(default='version1_default', max_length=30),
        ),
    ]
